name: CI
on:
  pull_request:
jobs:
  pkg_deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting up the environment
      run: npm install && npm run pkg-build && sudo npm link
    - name: Deploying version
      run: sudo deploy-pkg npm-package-deployer --npm-access-token=${{secrets.NPM_AUTH_TOKEN}} --github-access-token=${{secrets.G_AUTH_TOKEN}} --github-owner=danitseitlin --github-repo=npm-package-deployer --dry-run --publish-pretty-output --debug
      env:
        NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
  action_deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting up the environment
      run: npm install
    - name: Deploying version
      uses: ./
      with:
        pkg_name: npm-package-deployer
        pkg_managers: '[github, npm]'
        npm_registry: registry.npmjs.org
        npm_access_token: ${{secrets.NPM_AUTH_TOKEN}}
        github_access_token: ${{secrets.G_AUTH_TOKEN}}
        dry_run: true
        debug: true
    - name: Deploying version for non existing pkg
      uses: ./
      with:
        pkg_name: npm-package-deployer-non
        pkg_managers: '[github, npm]'
        npm_registry: registry.npmjs.org
        npm_access_token: ${{secrets.NPM_AUTH_TOKEN}}
        github_access_token: ${{secrets.G_AUTH_TOKEN}}
        dry_run: true
        debug: true